# 4. TO DO Task
## 4.1 Exercise on Functions:

### Task 1


In [ ]:
def convert_units(conversion_type, value):
  '''
  This function performs conversion based on the selected type.

  Parameters:
  conversion_type (int): This is the specific conversion formula to apply.
  value (value): This is the numeric value to be converted.

  Returns:
  float: The converted value
  '''
  # Length conversions

  # m to ft
  if conversion_type == 1: return value *3.28084
  #ft to m
  if conversion_type == 2: return value / 3.28084

  # Weight conversions

  # kg to lbs
  if conversion_type == 3: return value * 2.20462
  # lbs to kg
  if conversion_type == 4: return value / 2.20462

  # Volume conversions

  # L to gal
  if conversion_type == 5: return value * 0.264172
  # gal to L
  if conversion_type == 6: return value / 0.264172

def main():
  print("---  Unit Converter ---")
  print("1: Meters to Feet    \n2: Feet to Meters")
  print("3: KG to Pounds      \n4: Pounds to KG")
  print("5: Liters to Gallons \n6: Gallons to Liters")

  try:
    choice = int(input("\nSelect any conversion (1-6): "))

    if choice not in range(1,7):
      print("Error. Choose between the given range.")
      return

    val = float(input("Enter any value to convert: "))

    result = convert_units(choice, val)
    print(f"Result: {result:.2f}")

  except ValueError:
    print("Invalid input! Please enter numbers only.")


main()



---  Unit Converter ---
1: Meters to Feet    
2: Feet to Meters
3: KG to Pounds      
4: Pounds to KG
5: Liters to Gallons 
6: Gallons to Liters

Select any conversion (1-6): 2
Enter any value to convert: 5.1
Result: 1.55


Task 2

In [ ]:
def calculate_sum(numbers):
  '''
  Calculates the total sum of a list of numbers.

  Parameters:
  numbers (list): A list of numeric values (int or float) to be summed.

  Returns:
  float/int: The total sum of the numbers.

  '''
  return sum(numbers)

def calculate_avg(numbers):
  '''
  Calculates the average of a list of numbers.

  Parameters:
  numbers (list): A list of numeric values to be averaged.

  Returns:
  float: The arithmetic mean of the numbers.

  '''
  return sum(numbers) / len(numbers)

def calculate_max(numbers):
  '''
  Finds the largest number in the list.

  Parameters:
  numbers (list): A list of numeric values to search.

  Returns:
  float/int: The maximum value found in the list.

  '''
  return max(numbers)

def calculate_min(numbers):
  '''
  Finds the smallest number in the list.

  Parameters:
  numbers (list): A list of numeric values to search.

  Returns:
  float/int: The minimum value found in the list.

  '''
  return min(numbers)

print("---  Math Operations ---")
print("Options: \n1: Sum \n2: Average \n3: Maximum \n4: Minimum")

try:
    choice = int(input("\nSelect an operation (1-4): "))

    if choice not in [1, 2, 3, 4]:
        print("Invalid choice. Please pick 1, 2, 3, or 4.")

    else:
        raw_input = input("Enter numbers separated by spaces (e.g., 10 20 30): ")
        num_list = [float(x) for x in raw_input.split()]

        if not num_list:
            print("The list is empty! Please enter some numbers.")
        else:
            # Perform the selected operation
            if choice == 1:
                print(f"Sum: {calculate_sum(num_list)}")
            elif choice == 2:
                print(f"Average: {calculate_avg(num_list)}")
            elif choice == 3:
                print(f"Maximum: {calculate_max(num_list)}")
            elif choice == 4:
                print(f"Minimum: {calculate_min(num_list)}")

except ValueError:
    print("Error: Please enter valid numbers only.")

---  Math Operations ---
Options: 
1: Sum 
2: Average 
3: Maximum 
4: Minimum

Select an operation (1-4): 1
Enter numbers separated by spaces (e.g., 10 20 30): 10 40 50
Sum: 100.0


## 4.2 Exercise on List Manipulation

In [ ]:
#This is the list being tested for every list manipulation exercise
test_list = [1, 2, 3, 4, 5, 6]

### 1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
    """Returns a new list containing every other element starting from the first."""
    return lst[::2]
print("Every other:", extract_every_other(test_list))

Every other: [1, 3, 5]


### 2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    """Returns the sublist from start to end inclusive using slicing."""
    return lst[start : end + 1]

print("Sublist:", get_sublist(test_list, 2, 4))

Sublist: [3, 4, 5]


### 3. Reverse a List Using Slicing

In [ ]:
def reverse_list(lst):
    """Reverses a list using slicing."""
    return lst[::-1]

print("Reversed List is:", reverse_list(test_list))

Reversed List is: [6, 5, 4, 3, 2, 1]


### 4. Remove the First and Last Elements

In [ ]:
def remove_first_last(lst):
    """Removes the first and last elements using slicing."""
    return lst[1:-1]

print("After removing first and last elements:", remove_first_last(test_list))

After removing first and last elements: [2, 3, 4, 5]


### 5. Get the First n Elements

In [ ]:
def get_first_n(lst, n):
    """Extracts the first n elements using slicing."""
    return lst[:n]

print("After getting the first 'n' elements:", get_first_n(test_list,3))

After getting the first 'n' elements: [1, 2, 3]


### 5. Get the Last n Elements

In [ ]:
def get_last_n(lst, n):
    """Extracts the last n elements using slicing."""
    return lst[-n:]

print("After getting the last 'n' elements:", get_last_n(test_list,3))

After getting the last 'n' elements: [4, 5, 6]


### 7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    """Returns every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]

print("After reverse skip:", reverse_skip(test_list))

After reverse skip: [5, 3, 1]


## 4.3 Exercise on Nested List:

In [ ]:
nest_list = [[1, 2, 2, 3], [4, 5, 6], [7, 8, 9]]

### 1. Flatten a Nested List:

In [ ]:
def flatten(lst):
  """Flattens a 2D nested list into a single list."""
  flattened = []
  for sublist in lst:
    for item in sublist:
      flattened.append(item)
  return flattened


print("The flattened list is:",flatten(nest_list))

The flattened list is: [1, 2, 2, 3, 4, 5, 6, 7, 8, 9]


### 2. Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
    """Extracts an element from a nested list given a list of indices."""
    result = lst
    for index in indices:
        result = result[index]
    return result

print("The extracted element is:",access_nested_element(nest_list, [1,2]))

The extracted element is: 6


### 3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    """Calculates the sum of all numbers in a nested list of any depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print("The sum of all the elements are:",sum_nested(nest_list))

The sum of all the elements are: 47


### 4. Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of elememts from the nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print("The list after removing a specific element is:",remove_element(nest_list,6))

The list after removing a specific element is: [[1, 2, 2, 3], [4, 5], [7, 8, 9]]


### 5. Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
    """Finds the maximum element in a nested list of any depth."""
    current_max = float('-inf')
    for item in lst:
        if isinstance(item, list):
            res = find_max(item)
        else:
            res = item
        if res > current_max:
            current_max = res
    return current_max

print("The maximum number from the list is:",find_max(nest_list))

The maximum number from the list is: 9


### 6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    """Counts how many times elem appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print("The element appears following times:",count_occurrences(nest_list,2))

The element appears following times: 2


### 7. Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
    """Flattens a list of lists of lists... into a single list."""
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)
    return flattened

print("The flattened list of lists is:",deep_flatten(nest_list))

The flattened list of lists is: [1, 2, 2, 3, 4, 5, 6, 7, 8, 9]


### 8. Nested List Average:

In [ ]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = deep_flatten(lst)
    if not flat_list:
        return 0
    return sum(flat_list) / len(flat_list)

print("The average of the list is:",average_nested(nest_list))

The average of the list is: 4.7


# 10. To - Do - NumPy

In [ ]:
import numpy as np

## 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem - 1: Array Creation:

In [ ]:
# 1. Empty 2x2
empty_arr = np.empty((2, 2))

# 2. All ones 4x2
ones_arr = np.ones((4, 2))

# 3. Fill value
filled_arr = np.full((3, 3), 7)
print("The 3*3 matrix filled with 7 is as follow:\n",filled_arr)

# 4. Zeros like another array
zeros_like = np.zeros_like(ones_arr)
print("\nThe matrix filled with 0 is as follow:\n",zeros_like)

# 5. Ones like another array
ones_like = np.ones_like(empty_arr)
print("\nThe matrix filled with 1 is as follow:\n",ones_like)

# 6. Convert list to array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\nThe array from list is:\n",arr_from_list)


The 3*3 matrix filled with 7 is as follow:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

The matrix filled with 0 is as follow:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

The matrix filled with 1 is as follow:
 [[1. 1.]
 [1. 1.]]

The array from list is:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

# 1. Range 10 to 49
range_arr = np.arange(10, 50)
print("1. Range 10-49:\n", range_arr)

# 2. 3x3 matrix 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0-8:\n", matrix_3x3)

# 3. 3x3 Identity matrix
identity = np.eye(3)
print("\n3. Identity Matrix:\n", identity)

# 4. Random size 30 and mean
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()
print(f"\n4. Mean of random array: {mean_val:.4f}")

# 5. 10x10 random with min/max
rand_10x10 = np.random.random((10, 10))
print(f"\n5. 10x10 Random = Min: {rand_10x10.min():.4f}, Max: {rand_10x10.max():.4f}")

# 6. Zero array size 10, replace 5th element with 1
z_arr = np.zeros(10)
z_arr[4] = 1
print("\n6. Zero array with 5th element as 1:\n", z_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border 1, Inside 0:\n", border_arr)

# 9. Checkerboard 8x8 pattern
checker = np.zeros((8, 8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n9. Checkerboard Pattern:\n", checker)

1. Range 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array: 0.5478

5. 10x10 Random = Min: 0.0242, Max: 0.9430

6. Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border 1, Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = [9,10]
w = [11,12]

print("1. Addition of x and y:\n", x + y)

print("\n2. Subtraction of x and y:\n", x - y)

print("\n3. Multiplying x's elements with 4:\n", x * 4)

print("\n4. Squared of all the elements of y:\n", y**2)

print("\nDot product of v and w:", np.dot(v, w))
print("Dot product of x and v:", np.dot(x, v))
print("Dot product of x and y:\n", np.dot(x, y))


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplying x's elements with 4:
 [[ 4  8]
 [12 20]]

4. Squared of all the elements of y:
 [[25 36]
 [49 64]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


### Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * inv(A) (Identity Matrix):\n", np.round(identity_check))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"\n2. Prove AB != BA:")
print("   AB:\n", AB)
print("   BA:\n", BA)
print("   Are they equal?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
lhs = (AB).T
rhs = np.dot(B.T, A.T)
print(f"\n3. Transpose Proof (AB)^T == B^T @ A^T: {np.allclose(lhs, rhs)}")

1. A * inv(A) (Identity Matrix):
 [[1. 0.]
 [0. 1.]]

2. Prove AB != BA:
   AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   Are they equal? False

3. Transpose Proof (AB)^T == B^T @ A^T: True


In [ ]:
# Solving Linear Equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

# Solving using Matrix Inverse
X = np.dot(np.linalg.inv(A_sys), B_sys)

print("\n--- Linear Equation Solver ---")
print(f"Solution vector X: {X}")
print(f"Decoded: x = {X[0]:.1f}, y = {X[1]:.1f}, z = {X[2]:.1f}")


--- Linear Equation Solver ---
Solution vector X: [ 2.  1. -2.]
Decoded: x = 2.0, y = 1.0, z = -2.0


## 10.2 Experiment: How Fast is Numpy?

### 1. Element-wise Addition:

In [ ]:
import time

# Set the size for experiments 1, 2, and 3
size = 1000000

# Prepare data for Python Lists
list1 = list(range(size))
list2 = list(range(size))

# Prepare data for NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

print("1. Element-wise Addition")

# Python List Addition (requires a loop or list comprehension)
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
print(f"Python List Time: {time.time() - start:.5f} seconds")

# NumPy Array Addition
start = time.time()
result_arr = arr1 + arr2
print(f"NumPy Array Time: {time.time() - start:.5f} seconds")

1. Element-wise Addition
Python List Time: 0.11971 seconds
NumPy Array Time: 0.00397 seconds


### 2. Element-wise Multiplication

In [ ]:
print("\n2. Element-wise Multiplication")

# Python List Multiplication
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
print(f"Python List Time: {time.time() - start:.5f} seconds")

# NumPy Array Multiplication
start = time.time()
result_arr = arr1 * arr2
print(f"NumPy Array Time: {time.time() - start:.5f} seconds")


--- 2. Element-wise Multiplication ---
Python List Time: 0.14468 seconds
NumPy Array Time: 0.00530 seconds


### 3. Dot Product

In [ ]:
print("\n3. Dot Product")

# Python List Dot Product
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
print(f"Python List Time: {time.time() - start:.5f} seconds")

# NumPy Array Dot Product
start = time.time()
dot_arr = np.dot(arr1, arr2)
print(f"NumPy Array Time: {time.time() - start:.5f} seconds")


--- 3. Dot Product ---
Python List Time: 0.43626 seconds
NumPy Array Time: 0.00291 seconds


### 4. Matrix Multiplication

In [ ]:
import time
import random

n = 1000

# create matrices
A = [[random.random() for j in range(n)] for i in range(n)]
B = [[random.random() for j in range(n)] for i in range(n)]

# result matrix
C = [[0 for j in range(n)] for i in range(n)]

start = time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Time using Python lists:", end - start, "seconds")

Time using Python lists: 361.3961956501007 seconds


In [ ]:
import numpy as np
import time

n = 1000

A = np.random.rand(n, n)
B = np.random.rand(n, n)

start = time.time()

C = np.dot(A, B)

end = time.time()

print("Time using NumPy:", end - start, "seconds")

Time using NumPy: 0.10393452644348145 seconds
